version: "3.8"

services:
  db:
    build: 
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  node-service:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend
      - frontend

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - node-service
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  db-data:
